language: c

before_install:
- sudo apt-get update -q
- sudo apt-get install -qq apt-transport-https python-docutils
- curl https://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
- sudo apt-get -q update
- sudo apt-get install libvarnishapi-dev
- wget https://repo.varnish-cache.org/source/varnish-4.0.2.tar.gz -O - | tar -xz

before_script:
- ./autogen.sh
- ./configure VARNISHSRC=varnish* --prefix=/usr
- make

script:
- make check -j4

compiler:
- clang
- gcc
