language: c

before_install:
- sudo apt-get update -q
- sudo apt-get install -qq apt-transport-https python-docutils
- curl https://repo.varnish-cache.org/debian/GPG-key.txt | sudo apt-key add -
- echo "deb https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
- echo "deb-src https://repo.varnish-cache.org/ubuntu/ precise varnish-4.0" | sudo tee /etc/apt/sources.list.d/varnish-cache.list
- sudo apt-get -q update
- sudo apt-get install varnish
- wget https://repo.varnish-cache.org/source/varnish-4.0.0.tar.gz -O - | tar -xz

before_script:
- ./autogen.sh
- ./configure VARNISHSRC=varnish* VMODDIR=`pwd`
- make

script:
- make check -j4

compiler:
- clang
- gcc
