language: c

before_install:
- sudo apt-get install -qq python-docutils

before_script:
- git clone git@github.com:varnish/Varnish-Cache.git varnish
- cd varnish
- git checkout 4.0
- ./configure
- make
- cd ..
- ./autogen.sh
- ./configure VARNISHSRC=varnish VMODDIR=`pwd`
- make

script:
- make check
